# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
pip install gmaps

Requirement already satisfied: gmaps in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (0.9.0)
Requirement already satisfied: six in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from gmaps) (1.15.0)
Requirement already satisfied: traitlets>=4.3.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from gmaps) (5.1.1)
Requirement already satisfied: ipython>=5.3.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from gmaps) (7.31.1)
Requirement already satisfied: geojson>=2.0.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from gmaps) (2.5.0)
Requirement already satisfied: ipywidgets>=7.0.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from gmaps) (7.6.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (3.0.20)
Requirement already satisfied: backcall in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: jedi>=0.16 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.18.1)
Requirement already satisfied: pexpect>4.3; sys_platform != "win32" in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (4.8.0)
Requirement already satisfied: pygments in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (2.11.2)
Requirement already satisfied: pickleshare in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: appnope; sys_platform == "darwin" in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.1.2)
Requirement already satisfied: setuptools>=18.5 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (47.1.1.post20200604)
Requirement already satisfied: decorator in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (5.1.1)
Requirement already satisfied: matplotlib-inline in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.1.2)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (6.9.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (0.2.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0; python_version >= "3.6" in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (1.0.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.2)
Requirement already satisfied: nbformat>=4.2.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (5.1.3)
Requirement already satisfied: wcwidth in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jedi>=0.16->ipython>=5.3.0->gmaps) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from pexpect>4.3; sys_platform != "win32"->ipython>=5.3.0->gmaps) (0.7.0)
Requirement already satisfied: tornado<7.0,>=4.2 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.0.4)
Requirement already satisfied: nest-asyncio in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.5.1)
Requirement already satisfied: jupyter-client<8.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (7.1.2)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.4.1)
Requirement already satisfied: notebook>=4.4.1 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (5.7.10)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.2.0)
Requirement already satisfied: jupyter-core in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.9.2)
Requirement already satisfied: pyzmq>=13 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (22.3.0)
Requirement already satisfied: entrypoints in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (0.3)
Requirement already satisfied: python-dateutil>=2.1 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.1)
Requirement already satisfied: terminado>=0.8.1 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.13.1)
Requirement already satisfied: prometheus-client in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.13.1)
Requirement already satisfied: nbconvert<6.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (5.5.0)
Requirement already satisfied: jinja2 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.2)
Requirement already satisfied: Send2Trash in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.8.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.18.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.11.3)
Requirement already satisfied: attrs>=17.4.0 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (21.4.0)
Requirement already satisfied: bleach in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (4.1.0)
Requirement already satisfied: testpath in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: mistune>=0.8.1 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: defusedxml in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.7.1)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.1.1)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.7.0)
Requirement already satisfied: packaging in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from bleach->nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.3)
Requirement already satisfied: webencodings in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from bleach->nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from packaging->bleach->nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.4.7)

Note: you may need to restart the kernel to use updated packages.

In [2]:
# Dependencies and Setup


import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from ipywidgets.embed import embed_minimal_html
# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
csv_file = "../output_data_YZ/cities.csv"

weather_df = pd.read_csv(csv_file)

weather_df.head()

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Latitude,Longitude,Date
0,hobart,AU,60.66,96,100,6.91,-42.8794,147.3294,1666664558
1,kloulklubed,PW,83.37,80,100,22.37,7.0419,134.2556,1666664560
2,nyahururu,KE,50.40,83,10,5.30,0.0421,36.3673,1666664588
3,kodiak,US,45.91,53,0,18.41,57.7900,-152.4072,1666664589
4,mporokoso,ZM,72.28,42,96,4.90,-9.3727,30.1250,1666664589

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
#configure gmaps
gmaps.configure(api_key=g_key)

#get locations and humidity
locations = weather_df[['Latitude', 'Longitude']].astype(float)
humidity = weather_df['Humidity'].astype(float)

#add heatmap
fig = gmaps.figure(center = [0,0] ,zoom_level = 2)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 2)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
# * Narrow down the DataFrame to find your ideal weather condition. For example:

#   * A max temperature lower than 80 degrees but higher than 70.

#   * Wind speed less than 10 mph.

#   * Zero cloudiness.

#   * Drop any rows that don't satisfy all three conditions. You want to be sure the weather is ideal.

clean_df = weather_df[(weather_df["Temperature"] >= 70) & (weather_df["Temperature"] <= 80) & (weather_df["Windspeed"] <= 20) & (weather_df["Cloudiness"] == 0)]
clean_df

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Latitude,Longitude,Date
9,rikitea,PF,73.69,79,0,15.43,-23.1203,-134.9692,1666664592
17,atuona,PF,76.64,73,0,16.22,-9.8000,-139.0333,1666664594
50,abu dhabi,AE,78.82,73,0,2.30,24.4667,54.3667,1666664607
156,guerrero negro,MX,72.39,33,0,15.68,27.9769,-114.0611,1666664642
169,maceio,BR,74.64,94,0,5.75,-9.6658,-35.7353,1666664647
182,campo grande,BR,74.75,50,0,6.91,-20.4428,-54.6464,1666664652
230,salalah,OM,75.29,73,0,4.61,17.0151,54.0924,1666664557
288,artesia,US,70.86,38,0,6.91,33.8658,-118.0831,1666664686
293,nizwa,OM,71.60,39,0,1.48,22.9333,57.5333,1666664688
306,northbrook,US,72.25,54,0,19.57,42.1275,-87.8289,1666664504
323,khanpur,PK,72.97,30,0,9.35,28.6453,70.6567,1666664697
361,high rock,BS,77.02,65,0,14.61,26.6208,-78.2833,1666664710
372,morondava,MG,74.55,78,0,4.23,-20.2833,44.2833,1666664716
389,jardim,BR,70.61,64,0,3.71,-21.4803,-56.1381,1666664668
404,port saint lucie,US,77.95,63,0,6.91,27.2939,-80.3503,1666664617
412,matao,BR,70.90,66,0,11.72,-21.6033,-48.3658,1666664731
440,san juan,AR,77.81,22,0,5.14,-31.5375,-68.5364,1666664503
449,marrakesh,MA,71.67,30,0,5.75,31.6315,-8.0083,1666664743
502,umarkot,PK,72.91,71,0,9.08,25.3616,69.7362,1666664764
537,kano,NG,71.49,83,0,0.00,12.0001,8.5167,1666664778
541,sur,OM,79.25,39,0,4.76,22.5667,59.5289,1666664578

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df = clean_df

# params 
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}


for index, row in hotel_df.iterrows():
    lat = row["Latitude"]
    lng = row["Longitude"]

    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {row['City']}.")
    response = requests.get(base_url, params=params).json()
    # print(json.dumps(response, indent=4, sort_keys=True))
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 9: rikitea.
Closest hotel is People ThankYou.
------------
Retrieving Results for Index 17: atuona.

/Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/Users/yuteng/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Closest hotel is Villa Enata.
------------
Retrieving Results for Index 50: abu dhabi.
Closest hotel is Beach Rotana.
------------
Retrieving Results for Index 156: guerrero negro.
Closest hotel is Casa Laguna, Bed & Breakfast.
------------
Retrieving Results for Index 169: maceio.
Closest hotel is Hotel Ponta Verde Maceió.
------------
Retrieving Results for Index 182: campo grande.
Closest hotel is Residencial e Hotel Sênior Salmos 23.
------------
Retrieving Results for Index 230: salalah.
Closest hotel is HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel.
------------
Retrieving Results for Index 288: artesia.
Closest hotel is Sheraton Cerritos Hotel.
------------
Retrieving Results for Index 293: nizwa.
Closest hotel is Orient Apartments.
------------
Retrieving Results for Index 306: northbrook.
Closest hotel is Courtyard by Marriott Chicago Deerfield.
------------
Retrieving Results for Index 323: khanpur.
Closest hotel is Ahmad Bartan store.
------------
Retrieving Results for Index 361: high rock.
Closest hotel is Hideaway Bahamas Beach Club.
------------
Retrieving Results for Index 372: morondava.
Closest hotel is La Case Bambou.
------------
Retrieving Results for Index 389: jardim.
Closest hotel is Estancia Hotel - Jardim MS.
------------
Retrieving Results for Index 404: port saint lucie.
Closest hotel is Best Western Port St. Lucie.
------------
Retrieving Results for Index 412: matao.
Closest hotel is Hotel Caiçara.
------------
Retrieving Results for Index 440: san juan.
Closest hotel is Hotel Provincial.
------------
Retrieving Results for Index 449: marrakesh.
Closest hotel is Les Jardins de La Koutoubia.
------------
Retrieving Results for Index 502: umarkot.
Closest hotel is Al-Qamar Boys Hostel.
------------
Retrieving Results for Index 537: kano.
Closest hotel is Royal Tropicana Hotel.
------------
Retrieving Results for Index 541: sur.
Closest hotel is Sur Plaza Hotel.
------------

In [7]:
hotel_df
hotel_df = hotel_df.rename(columns={"Latitude": "Lat", "Longitude": "Lng"})
hotel_df

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Lat,Lng,Date,Hotel Name
9,rikitea,PF,73.69,79,0,15.43,-23.1203,-134.9692,1666664592,People ThankYou
17,atuona,PF,76.64,73,0,16.22,-9.8000,-139.0333,1666664594,Villa Enata
50,abu dhabi,AE,78.82,73,0,2.30,24.4667,54.3667,1666664607,Beach Rotana
156,guerrero negro,MX,72.39,33,0,15.68,27.9769,-114.0611,1666664642,"Casa Laguna, Bed & Breakfast"
169,maceio,BR,74.64,94,0,5.75,-9.6658,-35.7353,1666664647,Hotel Ponta Verde Maceió
182,campo grande,BR,74.75,50,0,6.91,-20.4428,-54.6464,1666664652,Residencial e Hotel Sênior Salmos 23
230,salalah,OM,75.29,73,0,4.61,17.0151,54.0924,1666664557,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
288,artesia,US,70.86,38,0,6.91,33.8658,-118.0831,1666664686,Sheraton Cerritos Hotel
293,nizwa,OM,71.60,39,0,1.48,22.9333,57.5333,1666664688,Orient Apartments
306,northbrook,US,72.25,54,0,19.57,42.1275,-87.8289,1666664504,Courtyard by Marriott Chicago Deerfield
323,khanpur,PK,72.97,30,0,9.35,28.6453,70.6567,1666664697,Ahmad Bartan store
361,high rock,BS,77.02,65,0,14.61,26.6208,-78.2833,1666664710,Hideaway Bahamas Beach Club
372,morondava,MG,74.55,78,0,4.23,-20.2833,44.2833,1666664716,La Case Bambou
389,jardim,BR,70.61,64,0,3.71,-21.4803,-56.1381,1666664668,Estancia Hotel - Jardim MS
404,port saint lucie,US,77.95,63,0,6.91,27.2939,-80.3503,1666664617,Best Western Port St. Lucie
412,matao,BR,70.90,66,0,11.72,-21.6033,-48.3658,1666664731,Hotel Caiçara
440,san juan,AR,77.81,22,0,5.14,-31.5375,-68.5364,1666664503,Hotel Provincial
449,marrakesh,MA,71.67,30,0,5.75,31.6315,-8.0083,1666664743,Les Jardins de La Koutoubia
502,umarkot,PK,72.91,71,0,9.08,25.3616,69.7362,1666664764,Al-Qamar Boys Hostel
537,kano,NG,71.49,83,0,0.00,12.0001,8.5167,1666664778,Royal Tropicana Hotel
541,sur,OM,79.25,39,0,4.76,22.5667,59.5289,1666664578,Sur Plaza Hotel

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [9]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

# Add the layer to the map
fig.add_layer(markers)

In [10]:
fig

Figure(layout=FigureLayout(height='420px'))